services:
  golang:
    build:
      context: ./build/golang
      #Select build stage
      target: dev
    env_file:
      - .env
    container_name: ${GOLANG_CONTAINER}
    volumes:
      - .:/app
    ports:
      - "${APP_LOCAL_PORT}:${APP_CONTAINER_PORT}"
  postgres:
    build:
      context: ./build/postgres
    env_file:
      - .env
    container_name: ${POSTGRES_CONTAINER}
    ports:
      - "${POSTGRES_LOCAL_PORT}:${POSTGRES_CONTAINER_PORT}"
    volumes:
      - data-store:/var/lib/postgresql/data
      - ./.tools/postgres:/var/lib/postgresql/schema
      
volumes:
  data-store:

