services:
  golang:
    build:
      context: .
      #Select build stage
      target: dev
    env_file:
      - .env
    container_name: ${GOLANG_CONTAINER}
    volumes:
      - .:/app
    ports:
      - "${APP_LOCAL_PORT}:${APP_CONTAINER_PORT}"


